unique_ids:
  assets:
    standard-page.html: XKNDRVZUBGN4772WXBZIXXK4FYJTXDZ5
    theme.css: JTIAJEA23SZSE437UJV5O64LPZ7R7G5T
  forms:
    ReviewForm: 644LHIO3R2ZCN3GEPYQU7UQGCAMBMWDS
  modules: {}
  scripts: {}
  server_modules:
    ReviewService: '1747784989092119984693082.45763'
